In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
# import numpy as np
# from sklearn.linear_model import LinearRegression
# 따라쓰기 연습

In [4]:
# reshape 코드입력
x = np.arange(10).reshape(-1, 1)
y = (2*x + 1).reshape(-1, 1)

In [5]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [6]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

## 모델의 선언, fit(학습), predict(예측)

In [7]:
# 모델 선언
model = LinearRegression()

In [8]:
model

LinearRegression()

In [9]:
# 학습
model.fit(x, y)

LinearRegression()

In [11]:
# 예측 # 예측값 10.0 투입
prediction = model.predict([[10.0]])

In [12]:
prediction

array([[21.]])